name: Deploy Multiple React Projects

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build MC-Que-1
        working-directory: MC-Que-1
        run: |
          npm install
          npm run build
          mkdir -p ../deploy/MC-Que-1
          cp -r dist/* ../deploy/MC-Que-1/
          echo '<meta http-equiv="refresh" content="0;url=/MC-Que-1/">' > ../deploy/index.html

      - name: Install and Build MC-Que-2
        working-directory: MC-Que-2
        run: |
          npm install
          npm run build
          mkdir -p ../deploy/MC-Que-2
          cp -r dist/* ../deploy/MC-Que-2/

      - name: Install and Build MC-Que-3
        working-directory: MC-Que-3
        run: |
          npm install
          npm run build
          mkdir -p ../deploy/MC-Que-3
          cp -r dist/* ../deploy/MC-Que-3/

      - name: Install and Build MC-Que-4
        working-directory: MC-Que-4
        run: |
          npm install
          npm run build
          mkdir -p ../deploy/MC-Que-4
          cp -r dist/* ../deploy/MC-Que-4/

      - name: Install and Build MC-Que-5
        working-directory: MC-Que-5
        run: |
          npm install
          npm run build
          mkdir -p ../deploy/MC-Que-5
          cp -r dist/* ../deploy/MC-Que-5/

      - name: Install and Build MC-Que-6
        working-directory: MC-Que-6
        run: |
          npm install
          npm run build
          mkdir -p ../deploy/MC-Que-6
          cp -r dist/* ../deploy/MC-Que-6/

      - name: Install and Build MC-Que-7
        working-directory: MC-Que-7
        run: |
          npm install
          npm run build
          mkdir -p ../deploy/MC-Que-7
          cp -r dist/* ../deploy/MC-Que-7/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: deploy # Deploy only the built projects
          clean: true
